### ISSUE TITLE
OS X, LibreOffice 4.4 and 5.0: no suitable office installation

### ISSUE THREAD

**Issue by pquentin** [dagwieers/unoconv#292]
As mentioned in #211, unoconv does not detect a suitable office installation on OS X (Yosemite) and LibreOffice 4.4 and 5.0. LibreOffice 4.3 works fine. When fixing manually the path searching to ensure that everything is found, the error becomes `ImportError: No module named 'com' (or 'com.sun.star.document.UpdateDocMode.QUIET_UPDATE' is unknown)`. Amusingly, this is the only import that breaks, but other things break anyway if we leave this out.

I think this is a bug in `find_offices` and `office_environ` only, because using the `python` binary from LibreOffice 4.4 and 5.0, this code works fine:

```
import uno
import unohelper

from com.sun.star.beans import PropertyValue
from com.sun.star.connection import NoConnectException
from com.sun.star.document.UpdateDocMode import QUIET_UPDATE
from com.sun.star.lang import DisposedException, IllegalArgumentException
from com.sun.star.io import IOException, XOutputStream
from com.sun.star.script import CannotConvertException
from com.sun.star.uno import Exception as UnoException
from com.sun.star.uno import RuntimeException
```

Since #211 is closed, I'll use this issue to document my progress, if any.

**Comment by hubgit** [comment]
I think this is fixed by https://github.com/dagwieers/unoconv/pull/276?

**Comment by shilpi230** [comment]
@dagwieers i tried on El captain with 4.4.6 it didn't work but as soon as i shifted to 4.3.5 it works :)

**Comment by pquentin** [comment]
@shilpi230 I did not continue to investigate as it was fixed in https://github.com/dagwieers/unoconv/pull/276. But no merge yet.

**Comment by dvandersluis** [comment]
Did anyone make any progress on this? With LO 5.1 it still doesn't work (but when I try it using the python binary it works, as per @pquentin).

**Comment by pquentin** [comment]
@dvandersluis What verison are you using? 0.7, or the master branch?

**Comment by dvandersluis** [comment]
I'm using master (prior to which I was getting the error about no suitable install found).

**Comment by SainteCelery** [comment]
I find this problem is ongoing. What is the workaround?

**Comment by brianedelman** [comment]
+1
